language: python
python: "3.2"
before_install:
  - deactivate
install:
  - sudo rm -f /etc/apt/sources.list.d/travis_ci_zeromq3-source.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3 python3-bs4 uwsgi uwsgi-plugin-python3 uwsgi-plugin-http
script:
  - dpkg-buildpackage -us -uc
  - sudo scripts/travis-install-and-setup-deb.sh
  - wget -O /dev/null http://localhost:9090/magdeburg/ovgu-unten.xml
after_script: sudo cat /var/log/uwsgi/app/openmensa-parsers.log
env:
  global:
    DEBEMAIL: packages@devtation.de
    DEBFULLNAME: "Travis CI Build VM"
