language: python
python: "3.2"
before_install:
  - deactivate
install:
  - sudo rm -f /etc/apt/sources.list.d/travis_ci_zeromq3-source.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3 uwsgi uwsgi-plugin-python3
  - which python3
  - python3 --version
script: dpkg-buildpackage -us -uc
after_success:
  - ls -lah ..
  - cat ../*.changes
  - dpkg --info ../openmensa-parsers_1.0*.deb
  - dpkg --contents ../openmensa-parsers_1.0*.deb
env:
  global:
    DEBEMAIL: packages@devtation.de
    DEBFULLNAME: "Travis CI Build VM"
