language: python
python: "3.2"
before_install:
  - deactivate
install:
  - sudo scripts/travis-install-deps.sh
before_script:
  - scripts/travis-prepare-packaging.sh
script:
  - dpkg-buildpackage -uc -us
  - sudo scripts/travis-install-and-setup-deb.sh
  - wget --output-document=/dev/null --input-file=test-urls.txt
after_success:
  - 'test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && scripts/travis-publish-package.sh'
after_script:
  - sudo cat /var/log/uwsgi/app/openmensa-parsers.log
  - cat /tmp/buildlog.txt
env:
  global:
    secure: BJRATzQDl81IRQvnz+EGz7WoDa5dHptN6VOQEuOC5/oOvGp1JlCUda/wQajCLUorbcN9pBN+FXhsKFzyOPoLg/63ANtiSKCsOvP9YZs1ZlXbu01qGiRdo1h1Qvy2W1qUrvFpkTgd3yq4gPVUmIaFs25SzOQQQqqT2kze1gv0Bac=
notifications:
  email:
    on_success: always
    on_failure: always
