language: python
python: "3.2"
install:
  - find /etc/apt
  - rm /etc/apt/sources.list.d/*zero*.list
  - sudo apt-get update
  - sudo apt-get install dpkg-dev debhelper uwsgi uwsgi-plugin-python3
script: dpkg-buildpackage -us -uc
after_success:
  - ls -lah ..
  - cat ../*.changes
  - dpkg --info ../openmensa-parsers_1.0*.deb
  - dpkg --contents ../openmensa-parsers_1.0*.deb
env:
  global:
    DEBEMAIL: packages@devtation.de
    DEBFULLNAME: "Travis CI Build VM"
